### ISSUE TITLE
[Request] Long-press clear all notification

### ISSUE THREAD

**Issue by Infinitay** [xyaman/tako#3]
Axon has the ability to long-press on the application group/cell and it would prompt you if you would like to clear all notifications respectively. It would be nice if Tako could have this feature.

**Comment by xyaman** [comment]
This already works. Swipe right, clear all. Swipe down, clear single app notifications.

**Comment by Infinitay** [comment]
I literally just found this out and came here to close the issue. Thank you nonetheless.
